import { AssistantConfig, AssistantPersona } from './types'

export const ASSISTANT_CONFIGS: Record<AssistantPersona, AssistantConfig> = {
  customer_booking: {
    id: 'customer_booking',
    nameEn: 'Booking Mitra',
    nameHi: 'बुकिंग मित्र',
    roleTitleEn: 'Service Finder & Price Guide',
    roleTitleHi: 'सेवा खोज व दर मार्गदर्शक',
    badgeEn: '⚡ Fast Matching',
    badgeHi: '⚡ त्वरित समाधान',
    avatar: '🛠️',
    greetingEn: 'Namaste! I am Booking Mitra, your Muzaffarnagar artisan guide. What household repair or service can I help you find today?',
    greetingHi: 'नमस्ते! मैं बुकिंग मित्र हूँ, आपका मुज़फ़्फ़रनगर कारीगर सहायक। आज आपको घर में किस मरम्मत या सेवा के लिए कारीगर चाहिए?',
    chips: [
      {
        id: 'cb_mcb',
        labelEn: '⚡ MCB Tripping / Fan Sparking',
        labelHi: '⚡ MCB ट्रिप या पंखे में स्पार्किंग',
        query: 'My fan is sparking and MCB trips repeatedly. Which electrician should I call and what is the fee in Muzaffarnagar?',
        icon: 'Zap',
      },
      {
        id: 'cb_leak',
        labelEn: '🚰 Water Pipe / Tank Leakage',
        labelHi: '🚰 पानी पाइप या टंकी लीकेज',
        query: 'I have a water leakage from my overhead tank/pipe in Civil Lines. Need a verified plumber urgently.',
        icon: 'Droplet',
      },
      {
        id: 'cb_clean',
        labelEn: '✨ Deep Home Cleaning Charges',
        labelHi: '✨ पूरे घर की डीप क्लीनिंग रेट्स',
        query: 'What are the charges for full house deep cleaning and kitchen cleaning in 251001?',
        icon: 'Sparkles',
      },
      {
        id: 'cb_salon',
        labelEn: '✂️ Salon & Grooming at Home',
        labelHi: '✂️ घर पर सैलून व ग्रूमिंग सेवा',
        query: 'Can I book a haircut, beard grooming, or women spa at home in Muzaffarnagar?',
        icon: 'Scissors',
      },
      {
        id: 'cb_pincode',
        labelEn: '📍 Coverage in New Mandi & Civil Lines',
        labelHi: '📍 नई मंडी व सिविल लाइन्स में उपलब्धता',
        query: 'Are artisans available in New Mandi (251001) and Civil Lines (251002)? How fast can they arrive?',
        icon: 'MapPin',
      },
      {
        id: 'cb_ac',
        labelEn: '❄️ AC Servicing & Cooling Issues',
        labelHi: '❄️ AC सर्विसिंग व कूलिंग समस्या',
        query: 'My split AC is not cooling properly and needs filter cleaning/gas check. What are standard visiting charges?',
        icon: 'Wind',
      },
    ],
  },

  customer_care: {
    id: 'customer_care',
    nameEn: 'Jugnu Care',
    nameHi: 'जुगनू समाधान',
    roleTitleEn: 'Customer Support & Issue Resolver',
    roleTitleHi: 'ग्राहक सहायता एवं समाधान',
    badgeEn: '🛡️ Priority Resolution',
    badgeHi: '🛡️ त्वरित सहायता',
    avatar: '🛡️',
    greetingEn: 'Hello! I am Jugnu Care. Have an ongoing booking, arrival delay, payment dispute, or need to reach our Admin desk?',
    greetingHi: 'नमस्कार! मैं जुगनू समाधान हूँ। क्या आपको किसी बुकिंग, कारीगर के आने में देरी, शुल्क विवाद या एडमिन डेस्क से संपर्क में सहायता चाहिए?',
    chips: [
      {
        id: 'cc_delay',
        labelEn: '⏱️ Artisan Delayed / Not Answering',
        labelHi: '⏱️ कारीगर लेट है / फोन नहीं उठा रहा',
        query: 'My booked artisan has not arrived on time and is not answering my call. What should I do?',
        icon: 'Clock',
      },
      {
        id: 'cc_pricing',
        labelEn: '💰 Charges Higher than Expected',
        labelHi: '💰 कारीगर ज़्यादा पैसे माँग रहा है',
        query: 'The artisan is quoting significantly higher charges than standard visiting fees. How can I resolve this?',
        icon: 'DollarSign',
      },
      {
        id: 'cc_cancel',
        labelEn: '📅 Reschedule or Cancel Booking',
        labelHi: '📅 बुकिंग रद्द या तारीख बदलें',
        query: 'How can I cancel or reschedule my active booking on Jugnu?',
        icon: 'Calendar',
      },
      {
        id: 'cc_quality',
        labelEn: '⚠️ Work Quality Complaint',
        labelHi: '⚠️ काम की गुणवत्ता से असंतुष्ट',
        query: 'The artisan completed the work but the repair is still faulty. How can I lodge an official complaint?',
        icon: 'AlertTriangle',
      },
      {
        id: 'cc_admin',
        labelEn: '📞 Talk Directly with Jugnu Admin',
        labelHi: '📞 जुगनू एडमिन से सीधी बात करें',
        query: 'I want to speak directly to the Jugnu administrator helpline right now.',
        icon: 'PhoneCall',
      },
    ],
  },

  worker_sarathi: {
    id: 'worker_sarathi',
    nameEn: 'Jugnu Sarathi',
    nameHi: 'जुगनू सारथी',
    roleTitleEn: 'Artisan Business & Duty Coach',
    roleTitleHi: 'कारीगर व्यवसाय व ड्यूटी मार्गदर्शक',
    badgeEn: '💼 Artisan Coach',
    badgeHi: '💼 आपका सच्चा साथी',
    avatar: '💼',
    greetingEn: 'Ram Ram! I am Jugnu Sarathi, your trusted partner. How can I assist you with duty alerts, customer WhatsApp messages, or 0% commission earnings?',
    greetingHi: 'राम-राम! मैं जुगनू सारथी हूँ। आज मैं आपको अधिक ग्राहक बुकिंग पाने, ग्राहक को सम्मानजनक व्हाट्सऐप मैसेज भेजने या 0% कमीशन नीति में कैसे मदद करूँ?',
    chips: [
      {
        id: 'ws_more_jobs',
        labelEn: '🔔 How to Get More Job Alerts?',
        labelHi: '🔔 ज़्यादा ग्राहक बुकिंग कैसे पाएँ?',
        query: 'How can I get more booking requests and phone calls from customers in Muzaffarnagar?',
        icon: 'TrendingUp',
      },
      {
        id: 'ws_wa_arrival',
        labelEn: '💬 WhatsApp Message: "I am On My Way"',
        labelHi: '💬 व्हाट्सऐप मैसेज: "मैं रास्ते में हूँ"',
        query: 'Give me a polite Hindi WhatsApp message to tell the customer that I am leaving and will reach in 20 minutes.',
        icon: 'MessageSquare',
      },
      {
        id: 'ws_payment',
        labelEn: '💵 0% Commission & Payment Rule',
        labelHi: '💵 0% कमीशन और भुगतान के नियम',
        query: 'Does Jugnu cut any commission from my earnings? How should I take payment from customers?',
        icon: 'Coins',
      },
      {
        id: 'ws_badge',
        labelEn: '⭐ Get Verified Gold Badge',
        labelHi: '⭐ वेरिफाइड गोल्ड बैज कैसे लें?',
        query: 'How can I get the Aadhaar Verified Gold Badge on my profile to earn customer trust?',
        icon: 'Award',
      },
      {
        id: 'ws_dispute',
        labelEn: '⚠️ Customer Refusing Visiting Charge',
        labelHi: '⚠️ ग्राहक विजिटिंग चार्ज देने से मना कर रहा',
        query: 'I visited the customer location, diagnosed the fault, but customer decided not to get it repaired and refuses inspection charge. What to do?',
        icon: 'ShieldAlert',
      },
      {
        id: 'ws_helpline',
        labelEn: '📞 Artisan Support Desk',
        labelHi: '📞 कारीगर सहायता हेल्पलाइन',
        query: 'Connect me with the Jugnu Artisan Support Desk on WhatsApp or phone call.',
        icon: 'Phone',
      },
    ],
  },
}

export const MUZAFFARNAGAR_KNOWLEDGE = {
  adminPhone: '+91 8077362606',
  adminPhoneRaw: '918077362606',
  supportedPincodes: ['251001', '251002'],
  keyAreas: [
    'New Mandi (नई मंडी)',
    'Civil Lines (सिविल लाइन्स)',
    'Roorkee Road (रुड़की रोड)',
    'Circular Road (सर्कुलर रोड)',
    'Gandhi Colony (गांधी कॉलोनी)',
    'Ansari Road (अंसारी रोड)',
    'Shiv Chowk / City (शिव चौक)',
    'Jansath Road (जानसठ रोड)',
    'Rampuram (रामपुरम)',
    'South Civil Lines (साउथ सिविल लाइन्स)',
    'Bharthal / Patel Nagar (पटेल नगर)',
  ],
  standardRates: {
    electrician: {
      visit: 'Provider-defined quote; Jugnu does not set a fixed visiting price.',
      scope: 'Switchboard / MCB fixing, wiring diagnosis, fan/light installation.',
    },
    plumber: {
      visit: 'Provider-defined quote; Jugnu does not set a fixed visiting price.',
      scope: 'Tap replacement, pipe leak repair, flush tank, motor pump priming.',
    },
    ac_repair: {
      visit: 'Provider-defined quote after reviewing the requested work.',
      scope: 'Inspection, filter deep wash, and gas pressure testing are quoted by the provider.',
    },
    part_time_maid: {
      visit: 'Provider-defined quote based on the requested work and property.',
      scope: 'Bathroom and full-home cleaning work are quoted by the provider.',
    },
    parlour_service: {
      visit: 'Provider-defined quote based on the requested service.',
      scope: 'Haircut, facial, grooming, nail care, mehendi and beauty care at home.',
    },
    carpenter: {
      visit: 'Provider-defined quote based on the requested work.',
      scope: 'Door lock fitting, hinge alignment, bed/wardrobe repair.',
    },
    painter: {
      visit: 'Provider-defined quote after reviewing the requested work.',
      scope: 'Interior wall painting, touch-up putty, waterproof coating quotation.',
    },
  },
}
